fix: force Append and Increment to return results and discard that result before returning it to user
Unoperate/java-bigtable-hbase-1 pull request #136
Opened 2021-11-03 16:26 UTC by prawilny

The name of the PR is WIP.
I only checked HBase 2.x behaviour for now.
We still probably need to implement similiar batch-append/increment result ignoring in https://github.com/Unoperate/java-bigtable-hbase-1/pull/116
The tests suddenly refused to be run so I leave it as a draft for now.

2021-11-11 23:57 UTC, prawilny commented
I didn't run the new integration tests yet.
Not implemended for AsyncMirroringBufferedMutator yet - will do it after a PR allowing us to create it from AsyncMirroringConnection.

2021-11-12 17:55 UTC, prawilny commented
I realized these tests may as well be unit tests rather than integration tests. Rebased the PR onto master.

2021-11-23 13:42 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/136)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java, line 84 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/136#-MpC-uYv-oQpXinwvDv6:-MpC-uYv-oQpXinwvDv7:b-6i1df0) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e9f5edaf05af7f728fdc78a9a1951046b6b3971b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java#L84)):*
> ```Java
>   }
> 
>   public static class RewrittenOperations<T extends Row> {
> ```

`RewrittenOperations` -> `RewrittenIncrementAndAppendIndicesInfo`?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java, line 92 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/136#-MpC0pHG8WbZ8ppXfsI0:-MpC0pHG8WbZ8ppXfsI1:b-u4810d) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e9f5edaf05af7f728fdc78a9a1951046b6b3971b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java#L92)):*
> ```Java
>      *   <li>HBase 1.4.12
>      *       <ul>
>      *         <li>append(Append): null
> ```

I'd ignore this behavior and put `Result.create(new Cell[0])` in batch operations, which will simplify this code.


<!-- Sent from Reviewable.io -->

2021-11-23 15:03 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/136)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java, line 84 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/136#-MpC-uYv-oQpXinwvDv6:-MpCGr443a8Ef7eQ9yVc:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e9f5edaf05af7f728fdc78a9a1951046b6b3971b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java#L84)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

`RewrittenOperations` -> `RewrittenIncrementAndAppendIndicesInfo`?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java, line 92 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/136#-MpC0pHG8WbZ8ppXfsI0:-MpCJbJF44HIbim_MPlH:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e9f5edaf05af7f728fdc78a9a1951046b6b3971b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java#L92)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I'd ignore this behavior and put `Result.create(new Cell[0])` in batch operations, which will simplify this code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 15:18 UTC, mwalkiewicz requested changes

2021-11-23 15:18 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +                assert ((Append) invocationOnMock.getArgument(0)).isReturnResults();
assertThat()

2021-11-23 15:18 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +  public void testAppendIncrementWhichDontWantResults() throws IOException, InterruptedException {
please split.

2021-11-23 15:18 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java
> +            if (op instanceof Increment) {
`||`

2021-11-23 15:18 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +    assertThat(appendIncrementWithoutResults[0]).isNull();
it shouldn't be null, right?

2021-11-23 16:11 UTC, prawilny commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/OperationUtils.java
> +            if (op instanceof Increment) {
Done.

2021-11-23 16:11 UTC, prawilny commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +  public void testAppendIncrementWhichDontWantResults() throws IOException, InterruptedException {
Done.

2021-11-23 16:11 UTC, prawilny commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +                assert ((Append) invocationOnMock.getArgument(0)).isReturnResults();
Done.

2021-11-23 16:11 UTC, prawilny commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +    assertThat(appendIncrementWithoutResults[0]).isNull();
Done.

2021-11-24 17:13 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +    executorServiceRule.waitForExecutor();
please remove.

2021-11-24 17:13 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +    executorServiceRule.waitForExecutor();
please remove.

2021-11-24 17:13 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +    executorServiceRule.waitForExecutor();
please remove.

2021-11-24 17:13 UTC, mwalkiewicz commented on bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringTable.java
> +    executorServiceRule.waitForExecutor();
please remove.

2021-11-25 14:46 UTC, mwalkiewicz approved these changes

2021-11-25 15:01 UTC, merged