MirroringAsyncTable#Batch()
Unoperate/java-bigtable-hbase-1 pull request #18
Opened 2021-09-21 15:31 UTC by prawilny

2021-09-23 21:19 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 34 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJPONr1T0pEbElnXE9:-MkJPONs2HvtTl4ZxyUf:b9nuo5y) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L34)):*
> ```Java
>       final MismatchDetector mismatchDetector,
>       final SecondaryWriteErrorConsumer secondaryWriteErrorConsumer) {
>     return createBatchVerificationCallback(
> ```

I'd move changes in this files to a separate PR.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 39 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJW5En0vV56TlaQYDi:-MkJW5En0vV56TlaQYDj:b-msri45) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L39)):*
> ```Java
>         mismatchDetector,
>         secondaryWriteErrorConsumer,
>         new Predicate<Object>() {
> ```

Would it be possible to pass this parameter explicitly in every place where it is used? maybe it's just too late for me, but I cannot conclude that this default value will always be correct, especially considering the fact that default predicate for SplitBatchResponse is different that this one.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 156 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJTxSu1z1-os0s87vD:-MkJTxSv0yRQ1nD8wbAq:b2l42wv) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L156)):*
> ```Java
> 
>   @Override
>   public <T> List<CompletableFuture<T>> batch(List<? extends Row> actions) {
> ```

Logic in this method is complicated and hard to follow. I think that it would be worth to split it into smaller parts. My favorite strategy of doing this is to walk through the code, add a comment above each 'portion' of code describing what it does, and then replacing those portions and corresponding comments with descriptively named methods.
Also, it might be worth to try replacing lambdas with non-inline methods or with named inline functions.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 158 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJ9CNnCuu19VAyAUEv:-MkJ9CNnCuu19VAyAUEw:bci66ye) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L158)):*
> ```Java
>   public <T> List<CompletableFuture<T>> batch(List<? extends Row> actions) {
>     final int numberOfActions = actions.size();
>     final ArrayList<CompletableFuture<T>> resultFutures =
> ```

The idiom in Java is to use `List<T> x = new ArrayList<>()`.
Also, you can try to use `Arrays.setAll(x, i -> new CompletableFuture<T>());` to fill the array instead of doing it manually.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 169 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJAx8q38fzWhGj0N_T:-MkJAx8q38fzWhGj0N_U:b-58qcot) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L169)):*
> ```Java
>     batchHelperWaitForAll(
>             primaryFutures,
>             (idx, throwable) -> {
> ```

Move this lambda to local variable and give it a some nice name (`primaryErrorHandler`?), it's hard to say what is its purpose now.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 203 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJSolk0Ss10KCGazz5:-MkJSolk0Ss10KCGazz6:b-6cq98b) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L203)):*
> ```Java
>                         new Object[primarySplitResponse.allSuccessfulOperations.size()];
> 
>                     reserveFlowControlResourcesThenScheduleSecondary(
> ```

I do not see body of `reserveFlowControlResourcesThenScheduleSecondary` in this PR, but maybe we can extract `scheduleSecondary` part out of it and not hack the former with passing completed futures?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 226 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJKb2yC9ExvZQJ3cqi:-MkJKb2zEvRZz-TxD8fu:bdzo1gv) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L226)):*
> ```Java
>   }
> 
>   private <T> CompletableFuture<Void> batchHelperWaitForAll(
> ```

This method accepts a flag that alters its behavior, what makes this code a bit convoluted. It can be simplified by moving the alternative behavior from this method into a separate wrapper method that will interpret results returned by this method. In code:

```
<T> CompletableFuture<Object[]> batchHelperWaitForAll(List<...> futures, Consumer<...> errorHandler) {
  ...
}
```
`Object[]` will be created inside this method and returned as a future.
We will accept the result in this form when handling results of primary operation.

We can use function similar to that below to handle the alternative behavior used when waiting for secondary batch results.
```
CompletableFuture<Void> getFutureFailingOnAnyBatchOperatoinFailure(CompletableFuture<Object[]> f) {
  CompletableFuture<Void> result = new ...;
  f.handle((result) -> {
    if (noError(result)) {
      result.complete(null);
    } else {
      result.fail(...)
    }
  });
  return result;
}
```
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 228 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJ8aw_-hiPYCGAIsoS:-MkJ8aw_-hiPYCGAIsoT:b-tc5a3z) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hb [...]

2021-09-23 21:41 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 226 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJKb2yC9ExvZQJ3cqi:-MkJacP29ph-zWbfAhKX:bngx5d2) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L226)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

This method accepts a flag that alters its behavior, what makes this code a bit convoluted. It can be simplified by moving the alternative behavior from this method into a separate wrapper method that will interpret results returned by this method. In code:

```
<T> CompletableFuture<Object[]> batchHelperWaitForAll(List<...> futures, Consumer<...> errorHandler) {
  ...
}
```
`Object[]` will be created inside this method and returned as a future.
We will accept the result in this form when handling results of primary operation.

We can use function similar to that below to handle the alternative behavior used when waiting for secondary batch results.
```
CompletableFuture<Void> getFutureFailingOnAnyBatchOperatoinFailure(CompletableFuture<Object[]> f) {
  CompletableFuture<Void> result = new ...;
  f.handle((result) -> {
    if (noError(result)) {
      result.complete(null);
    } else {
      result.fail(...)
    }
  });
  return result;
}
```
</blockquote></details>

Or maybe it would be better to wrap `BatchHelpers.createBatchVerificationCallback`?


<!-- Sent from Reviewable.io -->

2021-09-27 13:55 UTC, prawilny reviewed
> Dismissed @mwalkiewicz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 158 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJ9CNnCuu19VAyAUEv:-MkbWsPu5rLzqd9vzGgx:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L158)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

The idiom in Java is to use `List<T> x = new ArrayList<>()`.
Also, you can try to use `Arrays.setAll(x, i -> new CompletableFuture<T>());` to fill the array instead of doing it manually.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 169 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJAx8q38fzWhGj0N_T:-MkbXBUn07aWNGCsdDPr:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L169)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Move this lambda to local variable and give it a some nice name (`primaryErrorHandler`?), it's hard to say what is its purpose now.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 203 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJSolk0Ss10KCGazz5:-MkMuCj7CKGL78F0mLJp:b-xlkbxx) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L203)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I do not see body of `reserveFlowControlResourcesThenScheduleSecondary` in this PR, but maybe we can extract `scheduleSecondary` part out of it and not hack the former with passing completed futures?
</blockquote></details>

Well, we do have `scheduleVerificationAfterSecondaryOperation`. I still don't think it's that bad - if you find yourself having a reservation but not its future, you can always call `CompletableFuture.completedFuture(reservation)`.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 226 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJKb2yC9ExvZQJ3cqi:-MkbUq_pB2Kges-g1xHH:b-6mua7b) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L226)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Or maybe it would be better to wrap `BatchHelpers.createBatchVerificationCallback`?
</blockquote></details>

Done. Previous version was stupid. When the error is to be ignored, we just use `whenComplete`.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 228 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJ8aw_-hiPYCGAIsoS:-MkbSyjeDJ3rST-9C2-k:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L228)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Maybe you can use `BiConsumer` here?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 34 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJPONr1T0pEbElnXE9:-MkMsgZRAgVZCT9EtYYn:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L34)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I'd move changes in this files to a separate PR.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 39 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJW5En0vV56TlaQYDi:-MkMshNJ-E0XMQWoEVmG:b-w3h5wd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L39)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Would it be possible to pass this parameter explicitly in every place where it is used? maybe it's just too late for me, but I cannot conclude that this default value will always be correct, especially considering the fact that default predicate for SplitBatchResponse is different that this one.
</blockquote></details>

Done, I copied 1:1 rather than sensibly. Now it's `(o) -> o == null || o instanceof Throwable` in MirroringTable and `(o) - > o instanceof Throwable in MirroringAsyncTable` (both classes have static Predicate member).


<!-- Sent from Reviewable.io -->

2021-09-27 13:57 UTC, prawilny commented
Possibly I messed up a little bit - I published the review and only then pushed local changes.

2021-09-27 17:09 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 156 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkJTxSu1z1-os0s87vD:-MkcDbobDEq2lLtj5GlP:bfwfjdo) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/32621fd314cd16f90ec55bd1fb7c97f7cb288fc8/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L156)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Logic in this method is complicated and hard to follow. I think that it would be worth to split it into smaller parts. My favorite strategy of doing this is to walk through the code, add a comment above each 'portion' of code describing what it does, and then replacing those portions and corresponding comments with descriptively named methods.
Also, it might be worth to try replacing lambdas with non-inline methods or with named inline functions.
</blockquote></details>

Done.
I still feel like it's still quite complicated but have no idea how to simplify this any further.


<!-- Sent from Reviewable.io -->

2021-09-28 16:49 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 15 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 150 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhIQfzAXbnviP-Hnw3:-MkhIQfzAXbnviP-Hnw4:b-41fa9t) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L150)):*
> ```Java
>   }
> 
>   @Override
> ```

Why did you change the location in file of these methods?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 175 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkh4zfb85Q5pZdrrMBO:-Mkh4zfc6Yo23iAMg5Ai:brq59zd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L175)):*
> ```Java
>     final List<CompletableFuture<T>> primaryFutures = this.primaryTable.batch(actions);
>     // Unfortunately, we cannot create T[].
>     final Object[] primaryResults = new Object[numberOfActions];
> ```

Why not return `primaryResults` from the future returned from `waitForAllWithErrorHandler`?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 205 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhCwO84hy30U03qRoT:-MkhCwO84hy30U03qRoU:b-h0uf77) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L205)):*
> ```
> verificationCreator
> ```
The function's name already says (or should say) what it does, so I think invoking it directly where you need it will increase readability (vs having the local variable).
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 226 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhC9ZY4q0tj_nykrjH:-MkhC9ZY4q0tj_nykrjI:b-xwcje5) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L226)):*
> ```Java
>   }
> 
>   private Function<Void, FutureCallback<Void>> createBatchVerificationCallbackWrapper(
> ```

I think the function name would be better if it followed the variable you're assigning its result to, i.e. `createBatchVerificationCreator()`.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 237 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhAjX7-kFx-_ohEubB:-MkhAjX7-kFx-_ohEubC:bn6kvc0) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L237)):*
> ```Java
>   }
> 
>   private Supplier<CompletableFuture<Void>> createSecondaryBatchFuturesCompletedFutureSupplier(
> ```

I think inlining this function would improve readability. IMO its name is harder to comprehend than what it actually it does.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 247 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkh9Fn61j-_xhUtK3-R:-Mkh9Fn61j-_xhUtK3-S:bvu6mtd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L247)):*
> ```
> completeResultFutures
> ```
Maybe `completeSuccessfulResultFutures` to indicate that failed ones are handled elsewhere?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 257 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhI0eY65SBz9TfXWRZ:-MkhI0eZBuZCv8MqMsbk:b55fkzr) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L257)):*
> ```Java
>   // Waits for all of the futures from the list to complete and then returns an exceptional future
>   // if and only if any of them completed exceptionally.
>   private <T> CompletableFuture<Void> waitForAllWithErrorHandler(
> ```

I think this can be implemented via `ListenableCounter`, which could make it a bit more readable, potentially.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 307 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhIEY13Is6xtf5gh1U:-MkhIEY13Is6xtf5gh1V:b-10pbv6) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L307)):*
> ```Java
>             return;
>           }
>           CompletableFuture<FlowController.ResourceReservation> reservationFuture =
> ```

In the other method in this file you've inlined this - I think the inlined version is more readable.


<!-- Sent from Reviewable.io -->

2021-09-29 12:33 UTC, prawilny commented
Rebased onto new master - had to adjust secondaryWriteErrorConsumer (and fix a bug from master introduced by a rebase (in BatchHelpers)).

2021-09-29 13:39 UTC, mwalkiewicz reviewed
> Reviewed 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @dopiera and @mwalkiewicz)



<!-- Sent from Reviewable.io -->

2021-09-29 16:51 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 257 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhI0eY65SBz9TfXWRZ:-MkmRmGU-2qWOlXBazMm:bqiapnc) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L257)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Noticed a bug in the current code and a problem with the ReferenceCounter implementation: if the list of requests is empty (it's stupid but possible, I think), in the current implementation we never complete the future and in the ReferenceCounter implementation there's a problem with initializing the counter (and with using the class not really as its should be used). 
Rewritten and simplified the code a bit using AtomicReference (I wanted to use non-atomic reference, but variables used by lambdas have to be final).


</blockquote></details>

Here's another idea:
```
for (int i = 0; i < futures.size(); ++i) {
    future.handleAsync((ignoredResult, error) -> errorHandler(i, error));
}
return CompletableFuture.allOf(futures);
```

WDYT?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 180 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkmIzrFD37_WNNjJZLl:-MkmIzrFD37_WNNjJZLm:b-z88vc9) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c21c3db023b61ad570fe1594129d8a4ae8766c37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L180)):*
> ```
> numberOfActions
> ```
I think these are called operations, not actions. Also, I think it is unnecessarily verbose - `numOperations` would be just as good, but shorter.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 181 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkmJZBf8RR_y9krruR8:-MkmJZBf8RR_y9krruR9:b-iu2yqf) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c21c3db023b61ad570fe1594129d8a4ae8766c37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L181)):*
> ```
> resultFuturesArray
> ```
Why do we need this intermediate construction variable?
```
new ArrayList(new CompletableFuture[numOperations]);
Collections.setAll()
```
That should do the job, no?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 213 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkmPstPE3y_aEUgMkwg:-MkmPstPE3y_aEUgMkwh:b7daq9h) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c21c3db023b61ad570fe1594129d8a4ae8766c37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L213)):*
> ```Java
>                           this.flowController.asyncRequestResource(
>                               writeOperationInfo.requestResourcesDescription));
>               final Object[] secondaryResults =
> ```

This may have a considerable size. Should we allocate it in the `resourceReservationRequest`'s continuation?


<!-- Sent from Reviewable.io -->

2021-09-30 10:56 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @beta, @dopiera, and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 257 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhI0eY65SBz9TfXWRZ:-Mkq5wU91O48wqevJg0o:b5n122w) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L257)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Here's another idea:
```
for (int i = 0; i < futures.size(); ++i) {
    future.handleAsync((ignoredResult, error) -> errorHandler(i, error));
}
return CompletableFuture.allOf(futures);
```

WDYT?
</blockquote></details>

Unfortunately, Java 8 doesn't have (and guava's are annotated with "@Beta") utilities for zipping streams nor a function which could be named `mapWithIndex` (and mapping a function to a list can be also done via a stream).

Additionally, this version doesn't adhere to the function's contract - it doesn't fill results appropriately.
The other problem is with the fact that it returns too early if some function errs or doesn't know about the exception (though that may be helped by having a boolean flag and returning some generic exception).

Final version (with poorly named variables) adressing these problems is not better than the code IMO:
```
  private <T> CompletableFuture<Void> waitForAllWithErrorHandler(
      List<CompletableFuture<T>> futures,
      BiConsumer<Integer, Throwable> errorHandler,
      Object[] results) {
    int numFutures = futures.size();
    AtomicReference maybeThrowable = new AtomicReference(null);

    List<CompletableFuture<Void>> futs = new ArrayList<>();
    for (int i = 0; i < numFutures; i++) {
      final int futureIdx = i;
      futs.add(
          futures
              .get(futureIdx)
              .handle(
                  (result, error) -> {
                    if (error != null) {
                      results[futureIdx] = error;
                      maybeThrowable.compareAndSet(null, error);
                      errorHandler.accept(futureIdx, error);
                    } else {
                      results[futureIdx] = result;
                    }
                    return null;
                  }));
    }
    return CompletableFuture.allOf(futs.toArray(new CompletableFuture[0]))
        .handle(
            (ignoredResult, ignoredError) -> {
              if (maybeThrowable.get() != null) {
                throw new UncheckedExecutionException((Throwable) maybeThrowable.get());
              } else {
                return null;
              }
            });
  }
```
WDYT?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 180 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkmIzrFD37_WNNjJZLl:-Mkq1FcK78jDtK5Sub2g:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c21c3db023b61ad570fe1594129d8a4ae8766c37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L180)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> numberOfActions
> ```
I think these are called operations, not actions. Also, I think it is unnecessarily verbose - `numOperations` would be just as good, but shorter.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 181 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkmJZBf8RR_y9krruR8:-Mkq3IQF5nePqG2LD7Fe:bwqfhlp) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c21c3db023b61ad570fe1594129d8a4ae8766c37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L181)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> resultFuturesArray
> ```
Why do we need this intermediate construction variable?
```
new ArrayList(new CompletableFuture[numOperations]);
Collections.setAll()
```
That should do the job, no?
</blockquote></details>

There seem to be no method to set all elements of a list nor a constructor from array. I used Stream API - seems to be a bit cleaner.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 213 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkmPstPE3y_aEUgMkwg:-Mkq52GwAVBKGRrVwH4m:brnttth) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c21c3db023b61ad570fe1594129d8a4ae8766c37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L213)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This may have a considerable size. Should we allocate it in the `resourceReservationRequest`'s continuation?
</blockquote></details>

Only in this place do we know the size of the array we need to create.
Also there are some assertions about size of the array (in BatchHelpers) and there seems to be no way to shorten an Array.
Ah, there are also a lot of allocations while splitting the results.


<!-- Sent from Reviewable.io -->

2021-09-30 14:02 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @beta, @dopiera, and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 257 at r6](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-MkhI0eY65SBz9TfXWRZ:-Mkr-JIb4nXE1V8RRwLf:bkd8iy9) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/27f503dc7b0836833ded570aa93bba66a38f1933/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L257)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Unfortunately, Java 8 doesn't have (and guava's are annotated with "@Beta") utilities for zipping streams nor a function which could be named `mapWithIndex` (and mapping a function to a list can be also done via a stream).

Additionally, this version doesn't adhere to the function's contract - it doesn't fill results appropriately.
The other problem is with the fact that it returns too early if some function errs or doesn't know about the exception (though that may be helped by having a boolean flag and returning some generic exception).

Final version (with poorly named variables) adressing these problems is not better than the code IMO:
```
  private <T> CompletableFuture<Void> waitForAllWithErrorHandler(
      List<CompletableFuture<T>> futures,
      BiConsumer<Integer, Throwable> errorHandler,
      Object[] results) {
    int numFutures = futures.size();
    AtomicReference maybeThrowable = new AtomicReference(null);

    List<CompletableFuture<Void>> futs = new ArrayList<>();
    for (int i = 0; i < numFutures; i++) {
      final int futureIdx = i;
      futs.add(
          futures
              .get(futureIdx)
              .handle(
                  (result, error) -> {
                    if (error != null) {
                      results[futureIdx] = error;
                      maybeThrowable.compareAndSet(null, error);
                      errorHandler.accept(futureIdx, error);
                    } else {
                      results[futureIdx] = result;
                    }
                    return null;
                  }));
    }
    return CompletableFuture.allOf(futs.toArray(new CompletableFuture[0]))
        .handle(
            (ignoredResult, ignoredError) -> {
              if (maybeThrowable.get() != null) {
                throw new UncheckedExecutionException((Throwable) maybeThrowable.get());
              } else {
                return null;
              }
            });
  }
```
WDYT?
</blockquote></details>

Done.
Note wrapping the rethrown exception into a CompletionException - I cannot force handle() to return a checked exception. On the other hand, it's not really a problem - allOf wraps inner exception into CompletionException if it isn't already one, so the result stays the same (only a few lines in a test had to be changed).


<!-- Sent from Reviewable.io -->

2021-09-30 14:43 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @beta, @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 180 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr6Rol7iv62m8MHirz:-Mkr6Rol7iv62m8MHis-:bn8c6hm) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L180)):*
> ```Java
>         Stream.generate(() -> new CompletableFuture<T>())
>             .limit(numActions)
>             .collect(Collectors.toList());
> ```

I think you want `Collectors.toCollection(ArrayList::new)` - otherwise you have no guarantee that `.get(idx)`, which you're using below is constant time.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 256 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr84mh9yFaZ-SEg9Na:-Mkr84mh9yFaZ-SEg9Nb:b-t477st) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L256)):*
> ```
> handledFutures
> ```
Why create a separate list rather than reuse the existing one?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 258 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr7IfQ7av_p9PEW618:-Mkr7IfQ7av_p9PEW619:b7qidop) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L258)):*
> ```
> futureIdx
> ```
What's wrong with `i`? ;) Even if you prefer `futureIdx`, why not do `for (int futureIdx = 0; futureIdx < numFutures; ++futureIdx)`?


<!-- Sent from Reviewable.io -->

2021-09-30 14:56 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @beta, @dopiera, and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 180 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr6Rol7iv62m8MHirz:-MkrBcG07B45Rqff6A7E:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L180)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think you want `Collectors.toCollection(ArrayList::new)` - otherwise you have no guarantee that `.get(idx)`, which you're using below is constant time.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 256 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr84mh9yFaZ-SEg9Na:-MkrBgQBALgvs0VWDOM5:blv1js3) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L256)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> handledFutures
> ```
Why create a separate list rather than reuse the existing one?
</blockquote></details>

We can allow allOf() to return only after we've already filled results[] so we need new futures. Otherwise allOf() races with then()/handle().
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 258 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr7IfQ7av_p9PEW618:-MkrC-zoEBMIEC0kOwWD:bhocpqk) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L258)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> futureIdx
> ```
What's wrong with `i`? ;) Even if you prefer `futureIdx`, why not do `for (int futureIdx = 0; futureIdx < numFutures; ++futureIdx)`?
</blockquote></details>

We need a final variable to use in lambda.


<!-- Sent from Reviewable.io -->

2021-09-30 15:03 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @beta, @dopiera, and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 256 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18#-Mkr84mh9yFaZ-SEg9Na:-MkrDiAeEeabTpmsp1Sw:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3dea55ff4d09ac5b96fd027d31a4050539e5b2f1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L256)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

We can allow allOf() to return only after we've already filled results[] so we need new futures. Otherwise allOf() races with then()/handle().
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-09-30 15:03 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @beta, @dopiera, and @mwalkiewicz)



<!-- Sent from Reviewable.io -->

2021-09-30 15:07 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @beta, @dopiera, and @mwalkiewicz)



<!-- Sent from Reviewable.io -->

2021-10-01 09:11 UTC, mwalkiewicz approved these changes
> Reviewed 1 of 3 files at r10, 4 of 5 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/18)* status: all files reviewed, 1 unresolved discussion (waiting on @beta)



<!-- Sent from Reviewable.io -->

2021-10-01 09:57 UTC, merged