refactor: `SecondaryWriteErrorConsumer` => `SecondaryWriteErrorConsumerWithMetrics` in `MirroringAsyncTable` and `MirroringAsyncConnection`
Unoperate/java-bigtable-hbase-1 pull request #36
Opened 2021-09-29 14:51 UTC by prawilny

In preparation for `MirroringAsyncTable#batch()` which uses BatchHelpers, which use `SecondaryWriteErrorConsumerWithMetrics`

2021-09-29 15:23 UTC, dopiera requested changes
Why mix the two things in one PR? Github doesn't charge us for additional PRs ;)

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/36#-:-Mkm87je6yltq0fZu8Xo:b1ori7j)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 58 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/36#-Mkm6zBU5QCurdZAIyK1:-Mkm6zBU5QCurdZAIyK2:b-l7adq9) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/1bb4de2c830cc919d871a09bbc2b4381c082d0a5/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L58)):*
> ```
> secondaryWriteErrorConsumerWithMetrics
> ```
I think the extra `WithMetrics` suffic doesn't make the code more readable. In fact, I think we're getting to memeWorthyVariableNameLengths ;). Could you please not change the variable/field names? 

I should have caught this in review, but I think that `SecondaryWriteErrorConsumerWithMetrics` was a perfect case for inheritance - had I caught that, we could hold it by the superclass.


<!-- Sent from Reviewable.io -->

2021-09-30 09:23 UTC, prawilny reviewed
I was lazy and thought the changes are small enough to slip by :)
I just split the PRs - the AsyncRequestScheduling one is up too.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/36#-:-Mkq-uUS3YuLLD7L4zup:b-spwmpw)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 58 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/36#-Mkm6zBU5QCurdZAIyK1:-Mkq-cG22DWmrTTjCftv:b-51qoor) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/1bb4de2c830cc919d871a09bbc2b4381c082d0a5/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L58)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> secondaryWriteErrorConsumerWithMetrics
> ```
I think the extra `WithMetrics` suffic doesn't make the code more readable. In fact, I think we're getting to memeWorthyVariableNameLengths ;). Could you please not change the variable/field names? 

I should have caught this in review, but I think that `SecondaryWriteErrorConsumerWithMetrics` was a perfect case for inheritance - had I caught that, we could hold it by the superclass.
</blockquote></details>

Removed the suffix


<!-- Sent from Reviewable.io -->

2021-09-30 14:25 UTC, dopiera approved these changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/36)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)



<!-- Sent from Reviewable.io -->

2021-09-30 14:45 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwalkiewicz)



<!-- Sent from Reviewable.io -->

2021-09-30 14:46 UTC, merged