Delay secondary database call
Unoperate/java-bigtable-hbase-1 pull request #4
Opened 2021-09-14 12:26 UTC by prawilny

2021-09-14 12:36 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZILEwDUv-ky9rE5os:-MjZILEwDUv-ky9rE5ot:bben6sx) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java#L73)):*
> ```Java
>   }
> 
>   public Callable<ListenableFuture<Result>> get(final Get gets) {
> ```

We decided to do some copypasting here rather than change AsyncTableWrapper in order not to change all places the functions are used.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java, line 50 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZI_QU5mRQJrXVFeMZ:-MjZI_QU5mRQJrXVFeM_:b-lz4n1s) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java#L50)):*
> ```Java
>       final ResourceReservation reservation = reservationRequest.get();
>       ListenableFuture<T> secondaryResultFuture = null;
>       try {
> ```

That's why `Supplier` would be better but it's from Java 8


<!-- Sent from Reviewable.io -->

2021-09-14 12:39 UTC, prawilny reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZILEwDUv-ky9rE5os:-MjZJEmO2-rZIYTK7VLw:bb80uhw) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java#L73)):*
> We decided to do some copypasting in order not to change all places the functions are used.
I mean in order not to change AsyncTableWrapper's interface.


<!-- Sent from Reviewable.io -->

2021-09-15 14:25 UTC, mwalkiewicz reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZILEwDUv-ky9rE5os:-Mjdn14DCOHM-T3kK-cE:b6uaqf1) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java#L73)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

> We decided to do some copypasting in order not to change all places the functions are used.
I mean in order not to change AsyncTableWrapper's interface.
</blockquote></details>

How about creating a method as below and using it all modified calls instead of `submitTask`?
```
<T> Callable<ListenableFuture<T>> createSubmitTaskCallable(Callable<T> task) {
  return new Callable<ListenableFuture<T>>() {
    @Override
    public ListenableFuture<T> call() {
       return submitTask(task);
    }
  };
}
```
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java, line 50 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZI_QU5mRQJrXVFeMZ:-Mjdpgdl66ZK3wjZ5pCo:b-rh8qb2) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java#L50)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

That's why `Supplier` would be better but it's from Java 8
</blockquote></details>

We are using guava anyways, maybe their Supplier implementation will fit our purpose? https://guava.dev/releases/20.0/api/docs/com/google/common/base/Supplier.html


<!-- Sent from Reviewable.io -->

2021-09-15 14:34 UTC, mwalkiewicz reviewed
Integration tests are not run automatically on GitHub actions, can you run them manually and confirm that it works?

`mvn clean compile verify -Penable-integration-tests,BigtableToHBaseLocalIntegrationTests -pl bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x,bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests`

(You might need to change `BigtableToHBaseLocalIntegrationTests` to a different name of a profile, because it has changed recently and I don't know which version this PR is based on, look it up in the integrations pom.xml, please)

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-:-MjdrWvN6534Q4femviU:btbei6r)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dopiera and @prawilny)



<!-- Sent from Reviewable.io -->

2021-09-15 14:41 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java, line 94 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjdscPQEIV-QL-C1E_G:-MjdscPQEIV-QL-C1E_H:b-dmeunw) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java#L94)):*
> ```Java
>     this.scheduleRequest(
>         new RequestResourcesDescription(result),
>         new Callable<
> ```

Can't we modify `MirroringResultScanner#next(context)` in the same way as we did with AsyncTableWrapper?


<!-- Sent from Reviewable.io -->

2021-09-15 21:58 UTC, dopiera requested changes
Please describe why you're doing the change. My understanding is that this is to fix the bug you discovered, i.e. requesting flow control too late, right?

Instead of passing around the callback to create a future, why not simply pass around the resource  reservation instead of `ResourceDescription`.  Correct me if I'm wrong, but I think that'd simplify things - one fewer inversion of control and no hard-to-explain APIs (you have to be pretty convincing to prove that `Callable<Future<T>>` is the easiest way of expressing your intent).

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-:-MjfPL_90gjxHJ2k5iNr:bhayzrb)* status: all files reviewed, 4 unresolved discussions (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java, line 91 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjfO2fH472rLIvCPQ-i:-MjfO2fH472rLIvCPQ-j:b-olf7h0) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java#L91)):*
> ```Java
>     final ScannerRequestContext context =
>         new ScannerRequestContext(this.originalScan, result, startingIndex);
> ```

Please don't piggy-back unrelated changes to PRs.


<!-- Sent from Reviewable.io -->

2021-09-16 07:31 UTC, prawilny reviewed
You are seemingly right: the reason for the change is twofold:
- firstly, it fixes the bug
- secondly, it introduces a way to hack a function call into the moment just after getting the resources I am using right now in MirroringAsyncTable order to - as we talked f2f - complete the future only after getting resources.
Passing the reservation seems to be the correct approach, indeed.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-:-MjhSpni4pCKNXjrbz7a:b8gxms7)* status: all files reviewed, 4 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java, line 91 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjfO2fH472rLIvCPQ-i:-MjhVZKRANwF1qZx-SAb:bucgz4a) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java#L91)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please don't piggy-back unrelated changes to PRs.
</blockquote></details>

The variable has to be final in order to be passed into the Callable.
Will fix it.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java, line 94 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjdscPQEIV-QL-C1E_G:-MjhVoGaChFqo9jaX_yJ:b-763w2z) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java#L94)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Can't we modify `MirroringResultScanner#next(context)` in the same way as we did with AsyncTableWrapper?
</blockquote></details>

Probably we can, but I'll try the reservation approach first.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZILEwDUv-ky9rE5os:-MjhW2RS5QRViD2HDrVJ:b-1vt1lw) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java#L73)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

How about creating a method as below and using it all modified calls instead of `submitTask`?
```
<T> Callable<ListenableFuture<T>> createSubmitTaskCallable(Callable<T> task) {
  return new Callable<ListenableFuture<T>>() {
    @Override
    public ListenableFuture<T> call() {
       return submitTask(task);
    }
  };
}
```
</blockquote></details>

Ah, right
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java, line 50 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZI_QU5mRQJrXVFeMZ:-MjhWANa8ZwZvq4pK3OL:b6uyfat) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java#L50)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We are using guava anyways, maybe their Supplier implementation will fit our purpose? https://guava.dev/releases/20.0/api/docs/com/google/common/base/Supplier.html
</blockquote></details>

Will see into it


<!-- Sent from Reviewable.io -->

2021-09-16 12:21 UTC, prawilny reviewed
As decided F2F, we eventually decided to go with the Supplier/Callable approach because of problems with interrupts in function synchronously getting ResourceReservation.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-:-MjiXttbA5ST6VgQRwoD:b8hgpzn)* status: all files reviewed, 3 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java, line 91 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjfO2fH472rLIvCPQ-i:-MjiYA66-C9wdTduugQ2:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java#L91)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

The variable has to be final in order to be passed into the Callable.
Will fix it.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java, line 94 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjdscPQEIV-QL-C1E_G:-MjiYNvQ190mgiwhmNoi:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringResultScanner.java#L94)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Probably we can, but I'll try the reservation approach first.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZILEwDUv-ky9rE5os:-MjiYDTf-W8b8Tg5bZLK:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/asyncwrappers/AsyncTableWrapper.java#L73)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Ah, right
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java, line 50 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-MjZI_QU5mRQJrXVFeMZ:-MjiYGFe59_ZwvX0ce-4:bv1i831) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/ab4a4a1552a5122e3abb1681334dd410bbb21c6b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/RequestScheduling.java#L50)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Will see into it
</blockquote></details>

Seems to be working well.


<!-- Sent from Reviewable.io -->

2021-09-16 12:21 UTC, prawilny commented
Ah, the integration tests passed on my machine.

2021-09-16 16:53 UTC, dopiera approved these changes
LGTM, but please make sure the description of why it's needed is in the commit message after squashing. Likewise, please make the title more specific - "Obtain resource reservation before scheduling secondary calls" or something along these lines.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4#-:-MjjONn5ECKyq8EHcOeZ:b29zshn)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz and @prawilny)



<!-- Sent from Reviewable.io -->

2021-09-17 12:48 UTC, mwalkiewicz reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @prawilny)



<!-- Sent from Reviewable.io -->

2021-09-17 12:49 UTC, mwalkiewicz approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/4)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @prawilny)



<!-- Sent from Reviewable.io -->

2021-09-17 12:53 UTC, merged