refactor: remove redundant writeWithControlFlow argument
Unoperate/java-bigtable-hbase-1 pull request #44
Opened 2021-10-01 14:14 UTC by prawilny

[info, not a commit message]
When rebasing batch() patch after merging OpenCensus into master I introduced a redundant argument not having noticed that both the error handlers are the same.
This PR removes this redundant argument in preparation for cleaner implementation of Increment/Append as a Put.

2021-10-01 14:51 UTC, mwalkiewicz requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 360 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44#-MkwK74f3IL43-In6mWv:-MkwK74f3IL43-In6mWw:b-8inmg6) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c36d3b8a7e02b5337af9623cd5400cb73a2d75be/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L360)):*
> ```Java
>     ArgumentCaptor<Put> argument = ArgumentCaptor.forClass(Put.class);
>     verify(secondaryWriteErrorConsumer, times(1))
>         .consume(eq(HBaseOperation.PUT), argument.capture());
> ```

Why are you using argument captor as the second argument and eq() check as the first one?


<!-- Sent from Reviewable.io -->

2021-10-01 15:01 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 360 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44#-MkwK74f3IL43-In6mWv:-MkwMixG6P4VhjT64-sH:b-qtb42o) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c36d3b8a7e02b5337af9623cd5400cb73a2d75be/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L360)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Why are you using argument captor as the second argument and eq() check as the first one?
</blockquote></details>

By mistake. Done.


<!-- Sent from Reviewable.io -->

2021-10-02 13:35 UTC, mwalkiewicz requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 358 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44#-Ml0CYX878uw6w8jMPuL:-Ml0CYX91VC9Kyo2ISSI:bbf6cbf) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/2e21ec51b9fcb0ac899047f9277fb8efacbc2234/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L358)):*
> ```Java
>     verify(secondaryTable, times(1)).put(put);
> 
>     ArgumentCaptor<Put> argument = ArgumentCaptor.forClass(Put.class);
> ```

Is this used now?


<!-- Sent from Reviewable.io -->

2021-10-05 12:43 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 358 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44#-Ml0CYX878uw6w8jMPuL:-MlFTkb9-hErGzOpTBCp:b-vdgqh7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/2e21ec51b9fcb0ac899047f9277fb8efacbc2234/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L358)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Is this used now?
</blockquote></details>

Sorry, fixed it now.


<!-- Sent from Reviewable.io -->

2021-10-06 11:58 UTC, mwalkiewicz approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopiera)



<!-- Sent from Reviewable.io -->

2021-10-06 12:12 UTC, merged