MirroringAsyncConfiguration
Unoperate/java-bigtable-hbase-1 pull request #5
Opened 2021-09-14 13:09 UTC by prawilny

This PR adds subclass of MirroringConfiguration to be used by 2.x client.

2021-09-14 13:16 UTC, prawilny commented
Changed base branch so that merges can be nicely chained.

2021-09-15 14:48 UTC, mwalkiewicz approved these changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopiera)



<!-- Sent from Reviewable.io -->

2021-09-16 12:25 UTC, prawilny commented
Rebased onto new version of ac/delaySecondaryRequest

2021-09-16 17:55 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5)* status: 8 of 9 files reviewed, 9 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[.github/workflows/main.yml, line 31 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjfTDZg0CQ7BrYN9lnE:-MjfTDZg0CQ7BrYN9lnF:bs0qn3f) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b315c2c3ac07ebf08027fb5a5957b9b30548a39c/.github/workflows/main.yml#L31)):*
> ```YAML
>       - name: verify 1.x
>         run: mvn --batch-mode --update-snapshots verify -pl bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x
>       - name: upload 1.x jars
> ```

Do we still need it? I though you solved the problem by pinning versions.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConfiguration.java, line 51 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjfTPIq9kB7FKdyI8DR:-MjfTPIq9kB7FKdyI8DS:bnki6pf) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b315c2c3ac07ebf08027fb5a5957b9b30548a39c/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConfiguration.java#L51)):*
> ```Java
>    * primary database. Set to {@code default} to use default HBase connection class.
>    */
>   public static final String MIRRORING_PRIMARY_ASYNC_CONNECTION_CLASS_KEY =
> ```

This makes no sense for HBase 1.x, right? If yes, I'm guessing the next step is to move the whole class into a package shared by both client versions. If that's the case, why not flip the order and start from moving this class into a separate package?
___
*[bigtable-hbase-mirroring-client-2.x-parent/pom.xml, line 29 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-Mjjj6Qt2NkrWoAHAcu7:-Mjjj6Qu7RSmxQ5GytnA:bjfman7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/pom.xml#L29)):*
> ```XML
>   <packaging>pom</packaging>
>   <name>${project.groupId}:${project.artifactId}</name>
>   <version>2.0.0-alpha2-SNAPSHOT</version>
> ```

Should this field be also annotated with the `<!-- {x-version-update:bigtable-client-parent:current} -->` comment?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml, line 35 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjjDoM2Q6foA8M_Bh-:-MjjjDoM2Q6foA8M_Bh0:be29bhe) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml#L35)):*
> ```XML
>     <groupId>com.google.cloud.bigtable</groupId>
>     <artifactId>bigtable-hbase-mirroring-client-2.x-parent</artifactId>
>     <version>2.0.0-alpha2-SNAPSHOT</version>
> ```

`<!-- {x-version-update:bigtable-client-parent:current} -->`?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml, line 41 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjjFJ66sHR7LFVw2tS:-MjjjFJ66sHR7LFVw2tT:be29bhe) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml#L41)):*
> ```XML
>   <packaging>jar</packaging>
>   <name>${project.groupId}:${project.artifactId}</name>
>   <version>2.0.0-alpha2-SNAPSHOT</version>
> ```

`<!-- {x-version-update:bigtable-client-parent:current} -->`?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java, line 21 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjiTda2qpACYXfv0do:-MjjiTda2qpACYXfv0dp:b5isma8) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java#L21)):*
> ```Java
> import org.apache.hadoop.conf.Configuration;
> 
> public class MirroringAsyncConfiguration extends MirroringConfiguration {
> ```

As a rule of thumb prefer composition over inheritance. It's hard to argue that HBase 2 configuration "is a" HBase 1 configuration. I think it would be better if you refactored the logic to be reused from `MirroringConfiguration` into a separate class, which would be used by both client versions.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java, line 44 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjeDVh64Gk6fhGn8f5:-MjjeDVh64Gk6fhGn8f6:bdwh1r3) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java#L44)):*
> ```Java
>         connectionConfig, conf, connectionClassKey, asyncConnectionClassKey);
>     String asyncConnectionClassName = conf.get(asyncConnectionClassKey);
>     if (!asyncConnectionClassKey.equalsIgnoreCase("default")) {
> ```

I think you meant `asyncConnectionClassName` rather than `asyncConnectionClassKey`. Please add a test to make sure this works.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 18 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjgDn_E_lO5CnfGJcv:-MjjgDn_E_lO5CnfGJcw:b-cru1ul) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L18)):*
> ```Java
> package com.google.cloud.bigtable.mirroring.hbase2_x;
> 
> public class MirroringAsyncConnection {}
> ```

Should it extend the the HBase connection?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncConfiguration.java, line 29 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjjbyA-jise-1E12Kb:-MjjjbyA-jise-1E12Kc:b-gkt5p) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncConfiguration.java#L29)):*
> ```Java
> 
> @RunWith(JUnit4.class)
> public class TestMirroringAsyncConfiguration {
> ```

This test is a copy-pasted version of the HBase 1.x test. I think it could be way shorter (test HBase 2.x specific stuff only) if you made the refactoring I mentioned in the previous comment.


<!-- Sent from Reviewable.io -->

2021-09-20 13:47 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5)* status: 0 of 37 files reviewed, 9 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[.github/workflows/main.yml, line 31 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjfTDZg0CQ7BrYN9lnE:-Mk2S6fd4tiDVT5wBAcO:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b315c2c3ac07ebf08027fb5a5957b9b30548a39c/.github/workflows/main.yml#L31)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Do we still need it? I though you solved the problem by pinning versions.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConfiguration.java, line 51 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjfTPIq9kB7FKdyI8DR:-Mk2SAJI9GobyydOvXZw:bai8lqv) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b315c2c3ac07ebf08027fb5a5957b9b30548a39c/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConfiguration.java#L51)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This makes no sense for HBase 1.x, right? If yes, I'm guessing the next step is to move the whole class into a package shared by both client versions. If that's the case, why not flip the order and start from moving this class into a separate package?
</blockquote></details>

It seems unclear what to pull out right now - I didn't couple this too tightly so it should be easy to take out later
___
*[bigtable-hbase-mirroring-client-2.x-parent/pom.xml, line 29 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-Mjjj6Qt2NkrWoAHAcu7:-Mk2SRtB-tPuwJYi30h0:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/pom.xml#L29)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Should this field be also annotated with the `<!-- {x-version-update:bigtable-client-parent:current} -->` comment?
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml, line 41 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjjFJ66sHR7LFVw2tS:-Mk2SShr4x-1wh0s9Hgc:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml#L41)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`<!-- {x-version-update:bigtable-client-parent:current} -->`?
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java, line 21 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjiTda2qpACYXfv0do:-Mk2SX6A-2hGYKbTY385:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java#L21)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As a rule of thumb prefer composition over inheritance. It's hard to argue that HBase 2 configuration "is a" HBase 1 configuration. I think it would be better if you refactored the logic to be reused from `MirroringConfiguration` into a separate class, which would be used by both client versions.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java, line 44 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjeDVh64Gk6fhGn8f5:-Mk2STV-E71tED-LNsUQ:b-7wso34) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConfiguration.java#L44)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think you meant `asyncConnectionClassName` rather than `asyncConnectionClassKey`. Please add a test to make sure this works.
</blockquote></details>

Not relevant anymore
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncConfiguration.java, line 29 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5#-MjjjbyA-jise-1E12Kb:-Mk2SXta3m33ob9boo-p:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/0af7f655df0bd07e2ad5cff50bebd32e8ff8db2d/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncConfiguration.java#L29)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This test is a copy-pasted version of the HBase 1.x test. I think it could be way shorter (test HBase 2.x specific stuff only) if you made the refactoring I mentioned in the previous comment.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-09-21 10:15 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/5)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)



<!-- Sent from Reviewable.io -->

2021-09-21 12:07 UTC, merged