Initial implementation of a subset of asynchronous HBase 2.x Mirroring Client
Unoperate/java-bigtable-hbase-1 pull request #6
Opened 2021-09-14 13:29 UTC by prawilny

Note that `ExecutorServiceRule` is copypasted from 1.x client. The reuse will have to wait for another PR.

2021-09-15 16:05 UTC, mwalkiewicz requested changes
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 7 of 9 files reviewed, 11 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 27 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeA9CKACoExjuuyQOP:-MjeA9CKACoExjuuyQOQ:b-b36ayc) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L27)):*
> ```Java
> import java.util.ArrayList;
> import java.util.List;
> import java.util.concurrent.*;
> ```

As I commented elsewhere, please do not use wildcart imports. You can configure your IDE to replace them with specific usages when the code is formatted.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 43 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdwCI44lV0BiMkDk0e:-MjdwCI44lV0BiMkDk0f:b-skjwm5) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L43)):*
> ```Java
> 
>   public MirroringAsyncConnection(
>       Configuration conf, /* AsyncRegion */ Object o, String clusterId, User user)
> ```

Please add a comment explaining why are we taking `Object` instead of `AsyncRegion` and why we can safely ignore it here.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdwe528oJ7MZuZ6co0:-Mjdwe528oJ7MZuZ6co1:b-sw2vs5) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L73)):*
> ```Java
>   }
> 
>   private <T> T construct(String className, Object... params) {
> ```

Those method are copy-pasted from V1, can't we create a helper package in V1 with those methods and use them here and in V1 connection constructor? It'll be easier to move them to a separate base project later.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 102 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdxIQ7696BVSMwgOvU:-MjdxIQ7696BVSMwgOvV:b5cxjbg) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L102)):*
> ```Java
>   }
> 
>   // TODO: use default method after implementing MirroringAsyncTableBuilder
> ```

I've seen that it is common in the codebase to assign someone to every TODO, e.g. `// TODO(aczajkowski): blah blah`.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 39 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdxdaq5aKsR8LhxGyV:-Mjdxdaq5aKsR8LhxGyW:b-rfdtdh) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L39)):*
> ```Java
> 
> public class MirroringAsyncTable<C extends ScanResultConsumerBase> implements AsyncTable<C> {
>   AsyncTable<C> primaryTable;
> ```

private final?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 40 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdxfOj6zsLgUztl8zC:-MjdxfOj6zsLgUztl8zD:b-rfdtdh) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L40)):*
> ```Java
> public class MirroringAsyncTable<C extends ScanResultConsumerBase> implements AsyncTable<C> {
>   AsyncTable<C> primaryTable;
>   AsyncTable<C> secondaryTable;
> ```

private final?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 41 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdxfnV2AZzVldT9O03:-MjdxfnV2AZzVldT9O04:b-rfdtdh) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L41)):*
> ```Java
>   AsyncTable<C> primaryTable;
>   AsyncTable<C> secondaryTable;
>   VerificationContinuationFactory verificationContinuationFactory;
> ```

private final?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 90 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mje-N9k-G6vrEPKFe3H:-Mje-N9k-G6vrEPKFe3I:bxeu72c) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L90)):*
> ```Java
>         .exists(get)
>         .handleAsync(
>             (result, err) -> {
> ```

I think that you can easily extract ifology and handling an error into a (static?) method taking the future to be completed and callable to be run in non-error case.

```
this.primaryTable.exists(get).handleAsync(primaryOperationResultCallback(future, () -> { ... }));
```

This also applies to all other method in this file.

Moreover, maybe it would be possible to extract more common components from those methods. In fact it would be great if we could create a method that could be called like this:
```
primaryOperationResultCallbackForReads(
  (result) -> new RequestResourceDescription(result),
  () -> { return this.secondaryTable.exists(get) },
  (result) -> this.verificationContinuationFactory.exists(get, result)
)
```
and something similar for writes.

This would abstract away resolving the future, which is the most repetitive part of this code.

Also, maybe then it would be nice to abstract creating and returning the future away by creating yet another method taking primary future and some callables as parameters, and use it everywhere.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 90 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeA_2FEa5y6qsPCC4W:-MjeA_2FEa5y6qsPCC4X:b6yziqz) ([raw file](https://github.com/unoperate/java-bigtable-hbas [...]

2021-09-15 16:21 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 7 of 9 files reviewed, 12 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 104 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeEBIE66vRAw0zAZe6:-MjeEBIE66vRAw0zAZe7:b-71352h) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L104)):*
> ```Java
>               return null;
>             },
>             executorService);
> ```

We can use `MoreExecutors.directExecutor()` here. It'll run the callback on the thread that completed the future. It will be consistent with other places in our codebase where an executor for callback is provided. Those callbacks are light-weight thus there shouldn't be any problem with using it.


<!-- Sent from Reviewable.io -->

2021-09-16 09:30 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 94 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjhvnst0AoXkmF3mw4K:-MjhvnsuBwBZepSSSODD:bwo3f6x) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L94)):*
> ```Java
>                 future.completeExceptionally(err);
>               } else {
>                 scheduleVerificationAndRequestWithFlowControl(
> ```

This method is blocking
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 242 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjhwBYrAx8PU53jhJIB:-MjhwBYrAx8PU53jhJIC:b905ur2) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L242)):*
> ```
> RequestScheduling.scheduleVerificationAndRequestWithFlowControl
> ```
This method is blocking, we should use something else.


<!-- Sent from Reviewable.io -->

2021-09-16 12:28 UTC, prawilny commented
Oh, didn't notice the review before.
Just force-pushed a version rebased onto new ac/AsyncMirroringConfiguration (which itself got rebased onto new ac/delaySecondaryRequest).

2021-09-16 12:38 UTC, prawilny commented
Rebased once again in order to fix an error fixed in the previous branch.

2021-09-16 13:11 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 5 of 9 files reviewed, 13 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 27 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeA9CKACoExjuuyQOP:-Mji_Fmy0Qirg8G5HYM6:b4if1ew) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L27)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

As I commented elsewhere, please do not use wildcart imports. You can configure your IDE to replace them with specific usages when the code is formatted.
</blockquote></details>

Oh, I did it in some automagical way (I feel like it was either `Ctrl + Shift + L` or `mvn com.coveo:fmt-maven-plugin:format`).
Edit: `alt+enter` did that, it turns out
Will fix it (already fixed the IDE configuration)!
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 43 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdwCI44lV0BiMkDk0e:-Mjig05B08CJJYprrG_f:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L43)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Please add a comment explaining why are we taking `Object` instead of `AsyncRegion` and why we can safely ignore it here.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdwe528oJ7MZuZ6co0:-Mjig5I23kewSIz1vz-S:b-xpxn13) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L73)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Those method are copy-pasted from V1, can't we create a helper package in V1 with those methods and use them here and in V1 connection constructor? It'll be easier to move them to a separate base project later.
</blockquote></details>

I thought we wanted not to have arbitrary class creation with any kind of public interface.
Will do later.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 102 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdxIQ7696BVSMwgOvU:-Mjigb-z7IuzH64boynn:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L102)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I've seen that it is common in the codebase to assign someone to every TODO, e.g. `// TODO(aczajkowski): blah blah`.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 39 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdxdaq5aKsR8LhxGyV:-MjigpQx5HzFegFq7Qi4:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L39)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

private final?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 40 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdxfOj6zsLgUztl8zC:-MjigpbS7pGLbS4M5dt2:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L40)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

private final?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 41 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdxfnV2AZzVldT9O03:-MjigpnVDx9-w_slpU_J:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L41)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

private final?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 90 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeA_2FEa5y6qsPCC4W:-Mjih0DW3e2pLKmav66U:b-swmd5u) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L90)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Nitpick: err -> error, I personally prefer to use full words in code (except int i in for loop and Exception e in catch block :D)
</blockquote></details>

I wanted to check what Marek would say about playing gophers :)
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 90 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mje-N9k-G6vrEPKFe3H:-MjihMsF0gsG0jFsSBbH:bebrt1w) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L90)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I think that you can easily extract ifology and handling an error into a (static?) method taking the future to be completed and callable to be run in non-error case.

```
this.primaryTable.exists(get).handleAsync(primaryOperationResultCallb [...]

2021-09-16 21:45 UTC, dopiera reviewed
I know you're still working on this (making flow control async), but I just made a first pass and left some comments.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-:-MjkZPNr1Q2IYK4qtHu_:b-8vv9ts)* status: 1 of 9 files reviewed, 14 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 242 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjhwBYrAx8PU53jhJIB:-MjkYVQZ8XPvOvyNnM0K:bultok7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L242)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Right, as said higher up I'll fix it
</blockquote></details>

nit: "control flow" is about which statement gets executed next (i.e. loops, ifs, etc.). What you want here is "flow control", which is how we control in influx of incoming requests.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureConverter.java, line 19 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdz-beBwu5xJUxD1TY:-MjkWQOb8M5x2b-L_jLq:b-9xnfuj) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureConverter.java#L19)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

I think it quite often complains on CI about me forgetting to run it so I have no idea why it wasn't caught.
</blockquote></details>

I'm hesitant about using this library - it has 12 uses and it was last updated in 2018. Isn't implementing these converters trivial enough to just do it by ourselves?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/ExecutorServiceRule.java, line 25 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjkZ2v0Dim56ls9U_Cd:-MjkZ2v0Dim56ls9U_Ce:b-tm6lx7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb5f35cd101d55635f4ce4610a26b2157e69808c/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/ExecutorServiceRule.java#L25)):*
> ```Java
> import org.junit.rules.ExternalResource;
> 
> // Copypaste from hbase1_x
> ```

It's OK if you leave that for later, but I'm afraid we'll all forget - would you mind creating an issue for every instance of such a TODO and refer them in relevant places?


<!-- Sent from Reviewable.io -->

2021-09-17 13:32 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 1 of 9 files reviewed, 14 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 27 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeA9CKACoExjuuyQOP:-Mjnf_4tBO6Y-1JvE35T:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L27)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Oh, I did it in some automagical way (I feel like it was either `Ctrl + Shift + L` or `mvn com.coveo:fmt-maven-plugin:format`).
Edit: `alt+enter` did that, it turns out
Will fix it (already fixed the IDE configuration)!
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 90 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mje-N9k-G6vrEPKFe3H:-Mjnfdnj--DkGVKGDZMh:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L90)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 94 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjhvnst0AoXkmF3mw4K:-MjnfgjC6okzvmIu8Yg2:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L94)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Yeah, only after rereading the code I realized we were waiting for the resources synchronously.
Will do.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 104 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeEBIE66vRAw0zAZe6:-Mjnfhjt-I-m2ThT4sWr:bwiaxvn) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L104)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We can use `MoreExecutors.directExecutor()` here. It'll run the callback on the thread that completed the future. It will be consistent with other places in our codebase where an executor for callback is provided. Those callbacks are light-weight thus there shouldn't be any problem with using it.
</blockquote></details>

As discussed f2f, I decided to try going with `handle()`, `thenAcceptBoth()`, ... without "Async" suffix which seem to run on the thread calling `complete()` (and some other "completion method" - see https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html).
Thus I just deleted `this.executorService` from MirroringAsyncTable for now.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 242 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjhwBYrAx8PU53jhJIB:-MjnsiVEDWsBh0YMm7T1:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L242)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

nit: "control flow" is about which statement gets executed next (i.e. loops, ifs, etc.). What you want here is "flow control", which is how we control in influx of incoming requests.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureConverter.java, line 19 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdz-beBwu5xJUxD1TY:-Mjnskeu1PsGtg_pY7gu:bsb49o5) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureConverter.java#L19)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'm hesitant about using this library - it has 12 uses and it was last updated in 2018. Isn't implementing these converters trivial enough to just do it by ourselves?
</blockquote></details>

I was sure I read it in guava docs but I can''t find it now. Without that argument it really looks like we should rewrite this. I'll do it (in another PR).
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/ExecutorServiceRule.java, line 25 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjkZ2v0Dim56ls9U_Cd:-MjntlJ37JXoJ8gnZe12:bqcasw7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb5f35cd101d55635f4ce4610a26b2157e69808c/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/ExecutorServiceRule.java#L25)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's OK if you leave that for later, but I'm afraid we'll all forget - would you mind creating an issue for every instance of such a TODO and refer them in relevant places?
</blockquote></details>

After the rewrite MirroringAsyncTable no longer has ExecutorService member (the continuations are run on the thread which completed the future - see the comments above), so the tests don't need this class, so I just removed it and an issue is no longer needed :)
Also, right now Mateusz is working on common package - maybe he will finish by the time MirroringAsyncTable starts needing this mock.
I'll create issues for such TODOs in future, too. 


<!-- Sent from Reviewable.io -->

2021-09-20 13:36 UTC, mwalkiewicz requested changes
> Reviewed 1 of 1 files at r2, 1 of 7 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 43 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdwCI44lV0BiMkDk0e:-Mk2G45I1uXo0KrRVZbG:b-aii3ki) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L43)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think that it should be said explicitly that it is not needed because we are using create async connection which will pass it to constructors of underlying connections.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdwe528oJ7MZuZ6co0:-Mk2L92rCjnaoX7lazDC:b-bp7r0k) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L73)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

I thought we wanted not to have arbitrary class creation with any kind of public interface.
Will do later.
</blockquote></details>

Later means in different PR or in different commit?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 131 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2H-Dw42agCT9C3gcR:-Mk2H-Dx2KnTqjLXLWh5:btk85gx) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L131)):*
> ```Java
>   }
> 
>   private <T> CompletableFuture<T> getWithVerificationAndFlowControl(
> ```

nit: we have `writeWithFlowControl`, let's make this method `readWithVerificationAndFlowControl`.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 145 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2MXVQ1oL92Z5csi_H:-Mk2MXVQ1oL92Z5csi_I:b711o2r) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L145)):*
> ```Java
>             RequestResourcesDescription resourcesDescription =
>                 resourcesDescriptionCreator.apply(primaryResult);
>             CompletableFuture<FlowController.ResourceReservation> resourceFuture =
> ```

nit: `resourceFuture` -> `resourceReservationFuture`? I had hard time to understand that it is when reading the code.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 150 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2ODRy3rk0jBKqmMVR:-Mk2ODRy3rk0jBKqmMVS:b-bo44ph) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L150)):*
> ```Java
>             reserveControlFlowResourcesThenScheduleSecondary(
>                     resourceFuture,
>                     primaryFuture,
> ```

We are passing this completed future to conform to the API that allows to make primary request and take resources reservation in parallel.
If we instead dropped support for taking the reservation in parallel we could make this method call more obvious (I initially thought that it is a bug that you pass an already completed future), and we wouldn't need to use `acceptBoth` that you said might have some caveats afair.

@dopiera do you think that acquiring resources in parallel to the primary operation is really necessary? It'll take either <1ms if resources are available or way longer than the primary operation if resources they are not, there seems to be almost no latency gain.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 187 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2I8rZ2H3LSwUkMneO:-Mk2I8rZ2H3LSwUkMneP:bc5mzei) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L187)):*
> ```Java
>   }
> 
>   private <T> CompletableFuture<T> reserveControlFlowResourcesThenScheduleSecondary(
> ```

ControlFlow -> FlowControl
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 205 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2JaC1-kGWbe8-jDQ-:-Mk2JaC23cds6clkB2UJ:bxdxv72) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L205)):*
> ```Java
>         .exceptionally(
>             t -> {
>               if (!reservationFuture.cancel(true)) {
> ```

This is copied from V1, can be moved to some static function named `cancelReservationFuture` somewhere, maybe in ResourceReservation?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureConverter.java, line 19 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdz-beBwu5xJUxD1TY:-Mk2KMMm9srNFQUbAAEx:b-rsl5wh) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureConverter.java#L19)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

I was sure I read it in guava docs but I can''t find it now. Without that argument it really looks like we should rewrite this. I'll do it (in another PR).
</blockquote></details>

FYI: this lib is mentioned here https://guava.dev/releases/23.0/api/docs/com/google/common/util/concurrent/FluentFuture.html


<!-- Sent from Reviewable.io -->

2021-09-21 07:35 UTC, prawilny commented
Rebased onto new ac/MirroringAsyncConfiguration cutting down on size of the patch by ca. 700 lines.
Sorry for forgetting that github tracks PRs to branches by name yesterday.

2021-09-21 08:20 UTC, prawilny reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 3 of 11 files reviewed, 7 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 43 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjdwCI44lV0BiMkDk0e:-Mk6PIiLC-LbWrigcsdy:b-sfjrm1) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L43)):*
> we are using create async connection which will pass it to constructors of underlying connections
Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 73 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mjdwe528oJ7MZuZ6co0:-Mk6PJth-da5SMFfMoxK:bb9r9dq) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L73)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Later means in different PR or in different commit?
</blockquote></details>

Different PR (if despite your comment pointing to guava docs recommending this package from yesterday, we eventually decide to rewrite this)
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 131 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2H-Dw42agCT9C3gcR:-Mk6QFFABkaO4m_6H_UK:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L131)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

nit: we have `writeWithFlowControl`, let's make this method `readWithVerificationAndFlowControl`.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 145 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2MXVQ1oL92Z5csi_H:-Mk6QJQ01-z1dtYw677d:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L145)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

nit: `resourceFuture` -> `resourceReservationFuture`? I had hard time to understand that it is when reading the code.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 187 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2I8rZ2H3LSwUkMneO:-Mk6QPmW406pDxN68Ymi:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L187)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

ControlFlow -> FlowControl
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 205 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2JaC1-kGWbe8-jDQ-:-Mk6QQES1Q6LfV1so1St:biqdhih) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L205)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

This is copied from V1, can be moved to some static function named `cancelReservationFuture` somewhere, maybe in ResourceReservation?
</blockquote></details>

Moved into FlowController's static function (it only uses `java.util.concurrentFuture`'s interface so it handles both Listenable and Completable future families)


<!-- Sent from Reviewable.io -->

2021-09-21 09:45 UTC, prawilny commented
Rebased again after adding a fix in MirroringAsyncConfig.

2021-09-21 13:32 UTC, prawilny commented
Changed base base and rebased again, so that rebase will be easy for the batch() PR.

2021-09-21 16:56 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 1 of 41 files reviewed, 7 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/FlowController.java, line 49 at r14](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk8GBiv5PKMZVcTSq02:-Mk8GBiv5PKMZVcTSq03:b1x0oto) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/57020507fe1b6bd71f1358623b1b62c066baf924/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/FlowController.java#L49)):*
> ```
> his
> ```
Please use gender-neutral forms.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 150 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2ODRy3rk0jBKqmMVR:-Mk8H4AE3tPoxopebhZG:bajd57) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L150)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We are passing this completed future to conform to the API that allows to make primary request and take resources reservation in parallel.
If we instead dropped support for taking the reservation in parallel we could make this method call more obvious (I initially thought that it is a bug that you pass an already completed future), and we wouldn't need to use `acceptBoth` that you said might have some caveats afair.

@dopiera do you think that acquiring resources in parallel to the primary operation is really necessary? It'll take either <1ms if resources are available or way longer than the primary operation if resources they are not, there seems to be almost no latency gain.
</blockquote></details>

As we spoke F2F, I don't think it matters.


<!-- Sent from Reviewable.io -->

2021-09-24 12:50 UTC, prawilny reviewed
Apart from including suggestions from reviews, I also made MirroringAsync{Table,Connection} use SecondaryWriteErrorConsumer and/or ReflectionConstructor. 

Also, I added tests of new method in FlowController MirroringTable#reserveFlowControlResourcesThenScheduleSecondary.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-:-MkMIXi50IIHiyIRebTw:b-2n3squ)* status: 1 of 41 files reviewed, 7 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/FlowController.java, line 49 at r14](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk8GBiv5PKMZVcTSq02:-MkMI6rx40nE0da6TjMA:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/57020507fe1b6bd71f1358623b1b62c066baf924/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/FlowController.java#L49)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> his
> ```
Please use gender-neutral forms.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 68 at r9](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk6tYuICOAt8onb38H7:-MkMI8-UA8Sphp1y08Oq:bdymm0h) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/cc98894ed1ace1fac97bbbe274c106f846ca3b80/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L68)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please add a description of this constructor, especially the part about the `pool`, which will be created if a `null` is passed.
</blockquote></details>

Removed unused `pool` - `pool` is only used in AsyncTable constructor (through a builder IIRC).
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 150 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2ODRy3rk0jBKqmMVR:-MkMlBiF6xMgrQQ-cHdD:btmz58a) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L150)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As we spoke F2F, I don't think it matters.
</blockquote></details>

Ok, I finally read the docs (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html) after meeting a strange behaviour while writing tests:
thenAcceptBoth would be a problem if `FlowController.asyncRequestResource()` converted into a `CompletableFuture` could be completed exceptionally (then we'd have no guarantees which exception is returned). I think that's not the case (please correct me if my imagination serves me poorly). So I think it's not a problem.

There stands the point about it being a bit unintuitive. I think it's not that bad - it's clunky only in a single place (might be a problem later on, though). On the other hand, writes now have a nice interface - rewriting it would require this function to get uglier to some form of
```
Future resultFuture;
primaryFuture.then(primaryResult -> {
    scheduleRequest(primaryResult, ...).then({
        result.future.complete(primaryResult);
    });
});
return resultFuture;
```
Also, I think that it is possible that the performance advantage is nonzero.
So my suggestion is: let's keep it for now - it can be easily simplified later on.


<!-- Sent from Reviewable.io -->

2021-09-24 15:34 UTC, mwalkiewicz requested changes
> Reviewed 1 of 30 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 2 of 42 files reviewed, 5 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 150 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2ODRy3rk0jBKqmMVR:-MkNDr3gByzcgMS4bJ8w:bgy1z7y) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L150)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Ok, I finally read the docs (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html) after meeting a strange behaviour while writing tests:
thenAcceptBoth would be a problem if `FlowController.asyncRequestResource()` converted into a `CompletableFuture` could be completed exceptionally (then we'd have no guarantees which exception is returned). I think that's not the case (please correct me if my imagination serves me poorly). So I think it's not a problem.

There stands the point about it being a bit unintuitive. I think it's not that bad - it's clunky only in a single place (might be a problem later on, though). On the other hand, writes now have a nice interface - rewriting it would require this function to get uglier to some form of
```
Future resultFuture;
primaryFuture.then(primaryResult -> {
    scheduleRequest(primaryResult, ...).then({
        result.future.complete(primaryResult);
    });
});
return resultFuture;
```
Also, I think that it is possible that the performance advantage is nonzero.
So my suggestion is: let's keep it for now - it can be easily simplified later on.
</blockquote></details>

The point about resource reservation returning an exception is a good one. Now, while I think about it, it might be possible, but RequestScheduling assumes that it is not - which is a bug.
Let's notice the fact that FlowController implementation can be provided by the user. The user might want to reject some of the reservations in case of contention, for example the flow controller might want to reject all reads by default unless there are a lot of unused tickets in flow controller pool. In such a case we should complete the result future normally and do not perform the secondary operation.

(Which makes me think that we should have an indicator what kind of request, read or write, is requesting the resources.)

This observation leads us to the point where we have to distinguish the exceptions, which makes using acceptBoth cumbersome. I'd go for separating handling those futures now.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 209 at r16](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MkNQv10AiECC4EdD1_o:-MkNQv10AiECC4EdD1_p:b-xk7e6q) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8d1975b14e285d1cbe9eadcb7766879a6606becb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L209)):*
> ```Java
>               // We assume that reservationFuture never is an exceptional future
>               FlowController.cancelRequest(reservationFuture);
>               if (t instanceof CompletionException) {
> ```

Can we move this logic into a separate method?


<!-- Sent from Reviewable.io -->

2021-09-24 16:10 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 2 of 42 files reviewed, 6 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/TestFlowController.java, line 223 at r16](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MkNZQA-EoXX8BxJQ57f:-MkNZQA-EoXX8BxJQ57g:b-atndrc) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8d1975b14e285d1cbe9eadcb7766879a6606becb/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/TestFlowController.java#L223)):*
> ```Java
>   @Test
>   public void testCancellingGrantedReservationFuture() {
>     ResourceReservation reservation =
> ```

You can use `ResourceReservation reservation = mock(ResourceReservation.class)` to achieve the same effect without manually creating the implementation.


<!-- Sent from Reviewable.io -->

2021-09-24 16:25 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 2 of 42 files reviewed, 7 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 123 at r16](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MkNbL7L2qzxzfihLaW4:-MkNbL7L2qzxzfihLaW5:b-keiu3f) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8d1975b14e285d1cbe9eadcb7766879a6606becb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L123)):*
> ```Java
>         new MirroringTable.WriteOperationInfo(increment),
>         primaryFuture,
>         () -> this.secondaryTable.increment(increment));
> ```

Increment and Append are now implemented using Put on secondary database. Please create an issue for changing this implementation after you merge this PR.


<!-- Sent from Reviewable.io -->

2021-09-27 10:54 UTC, prawilny reviewed
Force-pushed as I unnecessarily merged MW's PR with 1.x changes into this one and then dropped these changes as reduntant.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-:-MkapdzODNwVedwxNrzF:b-cee1jn)* status: 2 of 44 files reviewed, 7 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/TestFlowController.java, line 223 at r16](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MkNZQA-EoXX8BxJQ57f:-Mkaq2DQ7qKljAznh1hf:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8d1975b14e285d1cbe9eadcb7766879a6606becb/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/flowcontrol/TestFlowController.java#L223)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

You can use `ResourceReservation reservation = mock(ResourceReservation.class)` to achieve the same effect without manually creating the implementation.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 104 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MjeEBIE66vRAw0zAZe6:-MkaqraI5Q7FbBknDSkv:bo61907) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b798b08c65e96964fc9940e81bd0f403fc3780d7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L104)):*
> f2f
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 150 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mk2ODRy3rk0jBKqmMVR:-Mkaq86p-gkOdVrDCeoj:b50eyd8) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/12f8bbb52a253a024d877fc3593c5eadc22d8ceb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L150)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

The point about resource reservation returning an exception is a good one. Now, while I think about it, it might be possible, but RequestScheduling assumes that it is not - which is a bug.
Let's notice the fact that FlowController implementation can be provided by the user. The user might want to reject some of the reservations in case of contention, for example the flow controller might want to reject all reads by default unless there are a lot of unused tickets in flow controller pool. In such a case we should complete the result future normally and do not perform the secondary operation.

(Which makes me think that we should have an indicator what kind of request, read or write, is requesting the resources.)

This observation leads us to the point where we have to distinguish the exceptions, which makes using acceptBoth cumbersome. I'd go for separating handling those futures now.
</blockquote></details>

Done. I also added passing the errors to faillog/secondaryWriteErrorHandler in case FlowController's reservation returns an exception.

Also, the last version uses the order of: primary request -> FlowController reservation -> secondary request and doesn't utilize simultaneous waiting for both futures.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 123 at r16](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MkNbL7L2qzxzfihLaW4:-MkaqLrT9mpoh9YH7YXu:bebrt1w) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8d1975b14e285d1cbe9eadcb7766879a6606becb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L123)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Increment and Append are now implemented using Put on secondary database. Please create an issue for changing this implementation after you merge this PR.
</blockquote></details>

Will do
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 209 at r16](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-MkNQv10AiECC4EdD1_o:-MkaqfQU3aZpgR2otqzU:b-6tgzq4) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8d1975b14e285d1cbe9eadcb7766879a6606becb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L209)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Can we move this logic into a separate method?
</blockquote></details>

After moving the scheduling methods to AsyncRequestScheduling I think the code got simpler if a bit verbose.


<!-- Sent from Reviewable.io -->

2021-09-27 11:57 UTC, mwalkiewicz requested changes
> Reviewed 2 of 18 files at r12, 29 of 30 files at r13, 1 of 5 files at r14, 3 of 5 files at r15, 1 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: 38 of 44 files reviewed, 3 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 194 at r18](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mkb3nv79kAwckQ_cJMI:-Mkb3nv79kAwckQ_cJMJ:bktu8aq) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b77d97f8d3527397bfe8f92dec74ba12767ad2bb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L194)):*
> ```Java
>               }
>             },
>         () -> controlFlowReservationErrorHandler.run());
> ```

why `() -> xxx.run()`?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/AsyncRequestScheduling.java, line 65 at r18](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mkb66il4abtULHL8Kjt:-Mkb66il4abtULHL8Kju:b-7urdeb) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b77d97f8d3527397bfe8f92dec74ba12767ad2bb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/AsyncRequestScheduling.java#L65)):*
> ```Java
>   }
> 
>   private static <T> void sendSecondaryRequestAndVerify(
> ```

This method is not sending any requests, maybe `scheduleVerificationAfterSecondaryOperation` would be a better name?


<!-- Sent from Reviewable.io -->

2021-09-27 12:16 UTC, prawilny reviewed
Changed as suggested; extracted some changed made unconnected with the rest of the code to another PR.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-:-MkbAW_961SwgbaUAce9:b-tfv5e2)* status: 35 of 44 files reviewed, 3 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 194 at r18](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mkb3nv79kAwckQ_cJMI:-MkbARzh0lKK_Vl8kdVL:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b77d97f8d3527397bfe8f92dec74ba12767ad2bb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L194)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

why `() -> xxx.run()`?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/AsyncRequestScheduling.java, line 65 at r18](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6#-Mkb66il4abtULHL8Kjt:-MkbAT2r-1UQDR89500u:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/b77d97f8d3527397bfe8f92dec74ba12767ad2bb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/AsyncRequestScheduling.java#L65)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

This method is not sending any requests, maybe `scheduleVerificationAfterSecondaryOperation` would be a better name?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-27 12:19 UTC, mwalkiewicz approved these changes
> Reviewed 1 of 18 files at r12, 1 of 5 files at r14, 1 of 4 files at r17, 6 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera)



<!-- Sent from Reviewable.io -->

2021-09-27 12:33 UTC, prawilny commented
Rebased

2021-09-27 12:38 UTC, mwalkiewicz approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/6)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dopiera)



<!-- Sent from Reviewable.io -->

2021-09-27 12:40 UTC, dopiera approved these changes

2021-09-27 12:45 UTC, merged