feat: MirroringAsyncBufferedMutator
Unoperate/java-bigtable-hbase-1 pull request #81
Opened 2021-10-15 09:13 UTC by kboroszko

Introducing MirroringAsyncBufferedMutator.

Mutate returns a future that gets completed only when the write to primary has completed and resources have been allocated for the secondary write.

2021-10-18 11:15 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @kboroszko, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java, line 60 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81#-Mm3ozX6C1opy_he3RbX:-MmI2fg1CPb77QxdbrnV:b-h95ecs) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e73426cfb77a82b1dc3678eadd3d950fd32108f9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java#L60)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I don't think this is true at the moment. Currently the future completes after the flow controller resources are acquired, decrementing the counter then wouldn't be appropriate.
</blockquote></details>

Agreed. Wrapping it wouldn't work, and I feel that restructuring it so there is a part that can be wrapped this way is much more obscure than calling the counter a few times.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java, line 129 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81#-Mm3iPie5k9dqxmYypSf:-MmI5pKp44S3BYrjpM1A:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e73426cfb77a82b1dc3678eadd3d950fd32108f9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java#L129)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

 "The implementation is required to be thread safe." -- https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/AsyncBufferedMutator.html
It is not thread-safe.

Right now the best close() implementation is probably the one in MirroringConnection - copy it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-18 12:25 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81)* status: 1 of 3 files reviewed, 15 unresolved discussions (waiting on @kboroszko, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java, line 74 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81#-Mm3nhlQDaJwOkexz0MS:-MmIH7hM0glE6UE-wrAv:b-uwbc58) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e73426cfb77a82b1dc3678eadd3d950fd32108f9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java#L74)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I do not argue for changing this code, but following the x.then().exceptionally() can lead to code that is less indented and that has error handling closer to code that can throw an error (now primary operation is handled at the top of the method, and its exceptions are handled at the very bottom). Those things make the code more readable.

I didn't try that, but isn't such a pattern possible?
```
CompletableFuture<Void> result = new CompletableFuture<>();
incrementRefCounter();

primaryFuture.exceptionaly((e) -> { result.exceptionally(e); decrementRef(); })
CompletableFuture<?> resourceAcquired = primaryFuture.thenCompose((ignored) -> flowController.async());
resourcesAcquired.exceptionally((e) -> { result.complete(null); decrementRef(); });
CompletableFuture<?> secondaryResult = resourcesAcquired.thenCompose((ignored) -> runSecondaryOp());
secondaryResult.exceptionally((e) -> { ... });
secondaryResult.thenRun(() -> decrementRef());
```

(But I'm a n00b in using java futures and I might be wrong and I do not have a code to test on :D )

What do you think?
</blockquote></details>

Cut the modesty, you're not a n00b and you know it! :hear_no_evil: I love it! There's one problem with this implementation though. You hook two `exceptionally` to the same primaryFuture. If the primary future fails, it triggers the first one, but it is also propagated further through thenCompose and to the second one. Worst part is, I don't really see a way around that other than nesting the futures like it is now...


<!-- Sent from Reviewable.io -->

2021-10-18 13:39 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81)* status: 1 of 3 files reviewed, 16 unresolved discussions (waiting on @kboroszko, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 96 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81#-MmIbKqT0YdOxwGqLQaP:-MmIbKqT0YdOxwGqLQaQ:b55atz9) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/bcbbfa23727a0b3e3237f4e5e2e53f3591b73229/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L96)):*
> ```Java
>     MIRRORING_CONNECTION_ABORT("MirroringConnection.abort"),
>     BUFFERED_MUTATOR_CLOSE("BufferedMutator.close"),
>     MIRRORING_BUFFERED_MUTATOR_CLOSE("MirroringBufferedMutator.close");
> ```

Is it used anywhere?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java, line 74 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81#-Mm3nhlQDaJwOkexz0MS:-MmIaZMSBacho33Xp58s:bbwkwde) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/e73426cfb77a82b1dc3678eadd3d950fd32108f9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java#L74)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Cut the modesty, you're not a n00b and you know it! :hear_no_evil: I love it! There's one problem with this implementation though. You hook two `exceptionally` to the same primaryFuture. If the primary future fails, it triggers the first one, but it is also propagated further through thenCompose and to the second one. Worst part is, I don't really see a way around that other than nesting the futures like it is now...
</blockquote></details>

And this is exactly why I said I'm a n00b, I knew that the code looks to pretty to be allowed by java :D I cannot see any better solution.

I'd approve now, but the code seems too simple for me and I want to check it again tomorrow if there isn't something that is missing :) Also, I'd be great to do some integration tests for this code, but the ITs project for 2.x is not ready yet. Adam was working on it and maybe he could share it with you tomorrow.


<!-- Sent from Reviewable.io -->

2021-10-19 11:18 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81)* status: 1 of 3 files reviewed, 15 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java, line 146 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81#-MmIctHf2IvQ0W2maacE:-MmNGUYj7dUFaygrLYzZ:b-hfpv0l) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/aa1e5d4f1f3d3bd7b474a08ac1d18df4729a87fd/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncBufferedMutator.java#L146)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Oh, ok, somehow I missed it. I would remove the scopes now, and we will add it later in a separate PR for every operation.
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2021-11-05 16:44 UTC, mwalkiewicz approved these changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/81)* status: all files reviewed, 15 unresolved discussions (waiting on @mwalkiewicz and @prawilny)



<!-- Sent from Reviewable.io -->

2021-11-05 16:45 UTC, merged